server:
  port: 7002
eureka:
  instance:
    hostname: peer2                 #eureka服务端的实例名称
  client:
    register-with-eureka: false       # false 表示不向服务注册中心注册自己
    fetch-registry: false             # false 表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://peer1:7001/eureka/,http://peer3:7003/eureka/